# The Machine Learning & Deep Learning Show

#### By Vedant Bahel & Harsh Aryan

In [313]:
#importing lib
import numpy as np
import pandas as pd

In [314]:
#importing data
dataset= pd.read_csv("IRIS.csv")

In [315]:
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [316]:
dataset["species"] = dataset["species"].astype('category')
dataset["Encoded_Species"] = dataset["species"].cat.codes

In [317]:
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width      species  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

   Encoded_Species  
0                0  
1                0  
2                0  
3                0  
4                0  


In [318]:
#define X & Y
X= dataset.iloc[:,0:4].values

In [319]:
Y= dataset.iloc[:,5].values

In [320]:
#split 
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y, test_size=0.1)

accuracy_results = {}

def cal_result(Y_test, Y_pred):
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(Y_test, Y_pred)
    return {'accuracy': accuracy}  

## Logistics Regression

In [321]:
from sklearn.linear_model import LogisticRegression
logclass= LogisticRegression()
logclass.fit(X_train, Y_train)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [322]:
Y_pred_log = logclass.predict(X_test)

In [323]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_results['Logistic Regression'] = cal_result(Y_test, Y_pred_log)

print(confusion_matrix(Y_test, Y_pred_log))
print(classification_report(Y_test, Y_pred_log))
print(accuracy_score(Y_test, Y_pred_log))

[[4 0 0]
 [0 6 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

1.0


## KNN Classifier

In [324]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(X_train, Y_train)
Y_pred_knn = knn.predict(X_test)

In [325]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_results['KNN Classifier'] = cal_result(Y_test, Y_pred_knn)


print(confusion_matrix(Y_test, Y_pred_knn))
print(classification_report(Y_test, Y_pred_knn))
print(accuracy_score(Y_test, Y_pred_knn))

[[4 0 0]
 [0 6 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

1.0


## Decision Tree

In [326]:
from sklearn.tree import DecisionTreeClassifier

## Complete the code
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

Y_pred_decision= classifier.predict(X_test)

accuracy_results['Decision Tree'] = cal_result(Y_test, Y_pred_decision)


print(confusion_matrix(Y_test, Y_pred_decision))
print(classification_report(Y_test, Y_pred_decision))
print(accuracy_score(Y_test, Y_pred_decision))

[[4 0 0]
 [0 6 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

1.0


## Random Forest

In [327]:
from sklearn.ensemble import RandomForestClassifier

## Complete the code
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

regressor = RandomForestClassifier(n_estimators=10, random_state=0)
regressor.fit(X_train, Y_train)
Y_pred_random = regressor.predict(X_test)

accuracy_results['Random Forest'] = cal_result(Y_test, Y_pred_random)


print(confusion_matrix(Y_test,Y_pred_random))
print(classification_report(Y_test,Y_pred_random))
print(accuracy_score(Y_test, Y_pred_random))

[[4 0 0]
 [0 6 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

1.0


## Which model performs best accuracy wise?

In [328]:
result = accuracy_results.values()
def get_accuracy(res):
    return res['accuracy']
max_accuracy = (max(result, key=get_accuracy))['accuracy']
print('Max Accuracy: ' + str(max_accuracy))

print('\nBest Models:')
for (method, res) in accuracy_results.items():
    if(res['accuracy'] == max_accuracy):
        print(method)

Max Accuracy: 1.0

Best Models:
Logistic Regression
KNN Classifier
Decision Tree
Random Forest
