In [2]:
#importing lib
import numpy as np
import pandas as pd

In [3]:
#importing data
dataset= pd.read_csv("predict_heart_diseases.csv")

In [4]:
print(dataset.head(len(dataset)))

      age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
5      39    1                3           120          339   
6      45    0                2           130          237   
7      54    1                2           110          208   
8      37    1                4           140          207   
9      48    0                2           120          284   
10     37    0                3           130          211   
11     58    1                2           136          164   
12     39    1                2           120          204   
13     49    1                4           140          234   
14     42    0                3           115          211   
15     5

In [5]:
#define X & Y
X= dataset.iloc[:,0:-1].values
Y= dataset.iloc[:,-1].values

In [6]:
#split 
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y, test_size=0.4)

accuracy_results = {}

def cal_result(Y_test, Y_pred):
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(Y_test, Y_pred)
    return {'accuracy': accuracy} 

In [7]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression
logclass= LogisticRegression()
logclass.fit(X_train, Y_train)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
Y_pred_log = logclass.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_results['Logistic Regression'] = cal_result(Y_test, Y_pred_log)

print(confusion_matrix(Y_test, Y_pred_log))
print(classification_report(Y_test, Y_pred_log))
print(accuracy_score(Y_test, Y_pred_log))

[[178  40]
 [ 38 220]]
              precision    recall  f1-score   support

           0       0.82      0.82      0.82       218
           1       0.85      0.85      0.85       258

   micro avg       0.84      0.84      0.84       476
   macro avg       0.84      0.83      0.83       476
weighted avg       0.84      0.84      0.84       476

0.8361344537815126


In [10]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(X_train, Y_train)
Y_pred_knn = knn.predict(X_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_results['KNN Classifier'] = cal_result(Y_test, Y_pred_knn)


print(confusion_matrix(Y_test, Y_pred_knn))
print(classification_report(Y_test, Y_pred_knn))
print(accuracy_score(Y_test, Y_pred_knn))

[[152  66]
 [ 75 183]]
              precision    recall  f1-score   support

           0       0.67      0.70      0.68       218
           1       0.73      0.71      0.72       258

   micro avg       0.70      0.70      0.70       476
   macro avg       0.70      0.70      0.70       476
weighted avg       0.71      0.70      0.70       476

0.7037815126050421


In [12]:
#Descision Tree

from sklearn.tree import DecisionTreeClassifier

## Complete the code
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

Y_pred_decision= classifier.predict(X_test)

accuracy_results['Decision Tree'] = cal_result(Y_test, Y_pred_decision)


print(confusion_matrix(Y_test, Y_pred_decision))
print(classification_report(Y_test, Y_pred_decision))
print(accuracy_score(Y_test, Y_pred_decision))

[[187  31]
 [ 46 212]]
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       218
           1       0.87      0.82      0.85       258

   micro avg       0.84      0.84      0.84       476
   macro avg       0.84      0.84      0.84       476
weighted avg       0.84      0.84      0.84       476

0.8382352941176471


In [13]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier

## Complete the code
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

regressor = RandomForestClassifier(n_estimators=10, random_state=0)
regressor.fit(X_train, Y_train)
Y_pred_random = regressor.predict(X_test)

accuracy_results['Random Forest'] = cal_result(Y_test, Y_pred_random)


print(confusion_matrix(Y_test,Y_pred_random))
print(classification_report(Y_test,Y_pred_random))
print(accuracy_score(Y_test, Y_pred_random))

[[196  22]
 [ 36 222]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       218
           1       0.91      0.86      0.88       258

   micro avg       0.88      0.88      0.88       476
   macro avg       0.88      0.88      0.88       476
weighted avg       0.88      0.88      0.88       476

0.8781512605042017


In [14]:
result = accuracy_results.values()
def get_accuracy(res):
    return res['accuracy']
max_accuracy = (max(result, key=get_accuracy))['accuracy']
print('Max Accuracy: ' + str(max_accuracy))

print('\nBest Models:')
for (method, res) in accuracy_results.items():
    if(res['accuracy'] == max_accuracy):
        print(method)

Max Accuracy: 0.8781512605042017

Best Models:
Random Forest
